// <auto-generated />
using BlazorEcomerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcomerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220927184454_AdingCategory2")]
    partial class AdingCategory2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEcomerce.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Name1",
                            URL = "Name_One"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Name2",
                            URL = "Name_two"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Name3",
                            URL = "Name_three"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CC",
                            URL = "Christina Carter"
                        });
                });

            modelBuilder.Entity("BlazroEcomerce.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Description 3 Description 3 Description 3 Description 3 Description 3 ",
                            ImgURL = "https://images.pexels.com/photos/762687/pexels-photo-762687.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Price = 700m,
                            Title = "Title 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Description 3",
                            ImgURL = "https://images.pexels.com/photos/768125/pexels-photo-768125.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Price = 1200m,
                            Title = "Title 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Description 3",
                            ImgURL = "https://images.pexels.com/photos/2237801/pexels-photo-2237801.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Price = 1300m,
                            Title = "Title 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Description 4",
                            ImgURL = "https://images.pexels.com/photos/762687/pexels-photo-762687.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Price = 730m,
                            Title = "Title 4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Description 5",
                            ImgURL = "https://images.pexels.com/photos/768125/pexels-photo-768125.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Price = 23200m,
                            Title = "Title 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Description 6",
                            ImgURL = "https://images.pexels.com/photos/2237801/pexels-photo-2237801.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Price = 13320m,
                            Title = "Title 6"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "A great Fucking pornstar",
                            ImgURL = "http://xxxnightrelax.com/image/867115.jpg",
                            Price = 100000000000m,
                            Title = "Christina Carter"
                        });
                });

            modelBuilder.Entity("BlazroEcomerce.Shared.Models.Product", b =>
                {
                    b.HasOne("BlazorEcomerce.Shared.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });
#pragma warning restore 612, 618
        }
    }
}
